### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by levin950825** [zxiaozhou/skillfull-cloud-vue#41]
api返回接收 list  key value 吧 或者 key label 而不是指定的CategoryCode之类的？一个成熟的SDK应该是字段解耦的

![CAC4D8E20DA6694930AEFA6398324E93](https://user-images.githubusercontent.com/13896536/195980744-207624d4-6660-452d-baf6-dea631cfcd7d.jpg)

**Comment by levin950825** [comment]
比如 categoryData 限制了必须要 CategoryCode 和 CategoryName

**Comment by zxiaozhou** [comment]
@levin950825 
1. update skillfull-process-pro-antvue to version 1.2.4
2. ts type
```
export interface Category {
  label: string;
  value: string;
  disabled?: boolean;
}
```
